services:
  frontend:
    build: ./oshi-front
    ports:
      - "3000:3000"
    volumes:
      - ./oshi-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - mynetwork

  backend:
    build: ./ohsi-back
    ports:
      - "8080:4000"
    volumes:
      - ./ohsi-back:/app  # 소스 코드가 변경될 때마다 반영
      - /app/build  # 빌드 디렉토리를 마운트하여 변경된 내용을 반영
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/oshi
      - SPRING_DATASOURCE_USERNAME=jasmin
      - SPRING_DATASOURCE_PASSWORD=d4583558
    depends_on:
      - db
    networks:
      - mynetwork
    command: >
      sh -c "gradle bootJar --no-daemon && java -jar /app/build/libs/*.jar"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: d4583558
      MYSQL_DATABASE: oshi
    ports:
      - "3307:3306"
    networks:
      - mynetwork 

networks:
  mynetwork:
    driver: bridge